Models/DTO/ReviewDTO.cs
using System.ComponentModel.DataAnnotations;

namespace OnlineStoreReviews.Models.DTO
{
    public class ReviewDTO
    {
        [Display(Name = "Ваше имя:")]
        [Required(ErrorMessage = "Укажите Ваше имя")]
        [MinLength(3, ErrorMessage = "Имя должно содержать хотя бы 3 символа")]
        public string? Author { get; set; }

        [Display(Name = "Текст отзыва:")]
        [DataType(DataType.MultilineText)]
        [Required(ErrorMessage = "Текст отзыва не может быть пустым")]
        [MinLength(3, ErrorMessage = "Текст отзыва должен содержать хотя бы 3 символа")]
        public string? Text { get; set; }
    }
}

Models/Entities/Cart.cs
namespace OnlineStoreReviews.Models.Entities
{
    public class Cart
    {
        public required int Id { get; set; }
        public List<CartItem> Items { get; set; } = new List<CartItem>();

        public void AddItem(Product product, int amount = 1)
        {
            foreach (CartItem item in Items)
            {
                if (item.ProductId == product.Id)
                {
                    item.Amount += amount;
                    return;
                }
            }

            CartItem newItem = new CartItem()
            {
                ProductId = product.Id,
                Amount = amount
            };

            Items.Add(newItem);
        }
    }
}

Models/Entities/CartItem.cs
namespace OnlineStoreReviews.Models.Entities
{
    public class CartItem
    {
        public int ProductId { get; set; }
        public int Amount { get; set; }
    }
}

Models/Entities/Product.cs
namespace OnlineStoreReviews.Models.Entities
{
    public class Product
    {
        public required int Id { get; set; }
        public required string Name { get; set; }
        public string? Description { get; set; }
        public required decimal Price { get; set; }
    }

    public class ProductDTO
    {
        public string? Name { get; set; }
        public string? Description { get; set; }
        public decimal? Price { get; set; }
    }
}

Models/Entities/Review.cs
namespace OnlineStoreReviews.Models.Entities
{
    public class Review
    {
        public required int Id { get; set; }
        public required string Author { get; set; }
        public required string Text { get; set; }
        public DateTime CreatedAt { get; set; } = DateTime.Now;
    }
}

Models/Utils/BreadcrumbItem.cs
namespace OnlineStoreReviews.Models.Utils
{
    public record BreadcrumbItem(
        string Text,
        string ControllerName,
        string ActionName
    );
}

Models/Views/FeaturesViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace OnlineStoreReviews.Models.Views
{
    public class FeaturesViewModel
    {
        [Display(Name = "Имя")]
        public string? FirstName { get; set; }

        [Display(Name = "Фамилия")]
        [DataType(DataType.Time)]
        public string? LastName { get; set; }
    }
}

Models/Views/ProductViewModel.cs
using OnlineStoreReviews.Models.DTO;
using OnlineStoreReviews.Models.Entities;

namespace OnlineStoreReviews.Models.Views
{
    public class ProductViewModel
    {
        public required Product Product { get; set; }
        public ReviewDTO? ReviewDTO { get; set; }
    }
}

Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineStoreReviews.Models.Entities;
using OnlineStoreReviews.Services;

namespace OnlineStoreReviews.Controllers
{
    public class CartController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/FeaturesController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineStoreReviews.Models.Views;

namespace OnlineStoreReviews.Controllers
{
    public class FeaturesController : Controller
    {
        public IActionResult Index()
        {
            FeaturesViewModel model = new FeaturesViewModel();
            return View(model);
        }

        public IActionResult ProcessRequest(FeaturesViewModel model)
        {
            return Content($"First name: {model.FirstName} / Last name: {model.LastName}");
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace OnlineStoreReviews.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineStoreReviews.Models.DTO;
using OnlineStoreReviews.Models.Entities;
using OnlineStoreReviews.Models.Utils;
using OnlineStoreReviews.Models.Views;
using OnlineStoreReviews.Services;

namespace OnlineStoreReviews.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IProductService _productService;
        private readonly ICartService _cartService;

        public ProductsController(IProductService productService, ICartService cartService)
        {
            _productService = productService;
            _cartService = cartService;
        }

        public IActionResult Index()
        {
            List<Product> products = _productService.GetProducts();

            ViewBag.Breadcrumb = new List<BreadcrumbItem>()
            {
                new BreadcrumbItem("Список товаров", "Products", "Index")
            };

            return View(products);
        }

        public IActionResult GetById([FromRoute] int? id)
        {
            if (id is null)
                return RedirectToAction("Index");

            Product? product = _productService.GetProductById((int) id);

            if (product is null)
                return RedirectToAction("Index");

            ProductViewModel model = new ProductViewModel()
            {
                Product = product,
                ReviewDTO = new ReviewDTO()
            };

            ViewBag.Breadcrumb = new List<BreadcrumbItem>()
            {
                new BreadcrumbItem("Список товаров", "Products", "Index"),
                new BreadcrumbItem(product.Name, "Products", "GetById")
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult AddProductReview([FromForm(Name = "ProductId")] int? id, [FromForm] ReviewDTO reviewDto)
        {
            if (id is null)
                return RedirectToAction("Index");

            Product? product = _productService.GetProductById((int) id);

            if (product is null)
                return RedirectToAction("Index");

            ProductViewModel model = new ProductViewModel()
            {
                Product = product,
                ReviewDTO = new ReviewDTO()
            };

            ViewBag.Breadcrumb = new List<BreadcrumbItem>()
            {
                new BreadcrumbItem("Список товаров", "Products", "Index"),
                new BreadcrumbItem(product.Name, "Products", "AddProductReview")
            };

            if (!ModelState.IsValid)
                return View("~/Views/Products/GetById.cshtml", model);

            return Content($"Author: {reviewDto.Author} / Text: {reviewDto.Text}");
        }

        [HttpGet]
        public IActionResult AddToCart([FromRoute] int? id)
        {
            if (id is null)
                return RedirectToAction("Index");

            Product? product = _productService.GetProductById((int) id);

            if (product is null)
                return RedirectToAction("Index");

            Cart cart = _cartService.GetCart();
            cart.AddItem(product);

            return RedirectToAction("GetById", new { id = id });
        }
    }
}

Views/Cart/Index.cshtml
@using OnlineStoreReviews.Services

@inject ICartService cartService
@inject IProductService productService

<p class="fs-4">Корзина</p>
<hr />

@{
    Cart cart = cartService.GetCart();
}

<ol>
    @foreach (CartItem cartItem in cart.Items)
    {
        Product? product = productService.GetProductById(cartItem.ProductId);

        if (product == null)
            continue;

        <li>
            @product.Name (@cartItem.Amount шт.)
        </li>
    }
</ol>

Views/Features/Index.cshtml
@using OnlineStoreReviews.Models.Views
@model FeaturesViewModel

@Html.CreateDateTime(DateTime.Now)

@{
    List<string> names = new List<string>()
    {
        "Tom",
        "Bob",
        "Alex"
    };
}

@Html.CreateOrderedList(names)

@using (Html.BeginForm("ProcessRequest", "Features", FormMethod.Post))
{
    @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "form-label" })
    @Html.DropDownListFor(model => model.FirstName, new SelectList(names), htmlAttributes: new { @class = "form-control" })

    @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "form-label" })
    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })

    <button type="submit">Отправить</button>
    @Html.Raw("<p>Test!</p>")
}

@Html.ActionLink("Hello, world!", "GetById", "Products", new { id = 1 })
<a asp-controller="Products" asp-action="GetById" asp-route-id="1">Hello, world!</a>

Views/Products/GetById.cshtml
@model ProductViewModel

<p class="fs-4">Информация о товаре</p>
<hr />

<a class="btn btn-success" asp-controller="Products" asp-action="AddToCart" asp-route-id="@Model.Product.Id">
    Добавить в корзину
</a>
<hr />

<table class="table table-stri">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Наименование свойства</th>
            <th scope="col">Значение свойства</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">1</th>
            <td>Название товара</td>
            <td>@Model.Product.Name</td>
        </tr>
        <tr>
            <th scope="row">2</th>
            <td>Описание товара</td>
            <td>@(Model.Product.Description ?? "Нет описания")</td>
        </tr>
        <tr>
            <th scope="row">3</th>
            <td>Цена товара</td>
            <td>@Model.Product.Price</td>
        </tr>
    </tbody>
</table>

@if (Model.ReviewDTO is not null)
{
    <p class="fs-4">Оставьте отзыв о товаре</p>
    <hr />

    @using (Html.BeginForm("AddProductReview", "Products", FormMethod.Post))
    {
        ReviewDTO reviewDto = Model.ReviewDTO;

        @Html.Hidden("ProductId", Model.Product.Id)

        <div class="mb-3">
            @Html.LabelFor(model => reviewDto.Author, htmlAttributes: new { @class = "form-label" })
            @Html.EditorFor(model => reviewDto.Author, new { htmlAttributes = new { @class = "form-control" } })
            <span class="text-danger" asp-validation-for="@reviewDto.Author"></span>
        </div>
        <div class="mb-3">
            @Html.LabelFor(model => reviewDto.Text, htmlAttributes: new { @class = "form-label" })
            @Html.EditorFor(model => reviewDto.Text, new { htmlAttributes = new { @class = "form-control" } })
            <span class="text-danger" asp-validation-for="@reviewDto.Text"></span>
        </div>
        <div class="mb-3">
            <button class="btn btn-primary" type="submit">Оставить отзыв</button>
        </div>
    }
}

Views/Products/Index.cshtml
@model List<Product>

<ol>
    @foreach (Product product in Model)
    {
        <li>
            <a asp-controller="Products" asp-action="GetById" asp-route-id="@product.Id">
                @product.Name
            </a>
        </li>
    }
</ol>

Views/Shared/_BreadcrumbPartial.cshtml
@{
    List<BreadcrumbItem> items = new List<BreadcrumbItem>()
    {
        new BreadcrumbItem("Главная страница", "Home", "Index")
    };

    if (ViewBag.Breadcrumb is not null)
        foreach (BreadcrumbItem item in ViewBag.Breadcrumb)
            items.Add(item);
}

<div class="container-md">
    @if (ViewBag.HasBreadcrumb)
    {
        @RenderSection("Breadcrumb", false)
    }
    else
    {
        string? currentControllerName = (string?) ViewContext.RouteData.Values["controller"];
        string? currentActionName = (string?) ViewContext.RouteData.Values["action"];

        bool IsBreadcrumbItemActive(BreadcrumbItem item)
        {
            return (currentControllerName == item.ControllerName) && (currentActionName == item.ActionName);
        }

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                @foreach (BreadcrumbItem item in items)
                {
                    if (IsBreadcrumbItemActive(item))
                    {
                        <li class="breadcrumb-item active" aria-current="page">
                            @item.Text
                        </li>
                    }
                    else
                    {
                        <li class="breadcrumb-item">
                            <a asp-controller="@item.ControllerName" asp-action="@item.ActionName">
                                @item.Text
                            </a>
                        </li>
                    }
                }
            </ol>
        </nav>
    }
</div>

Views/Shared/_Layout.cshtml
@{
    ViewBag.HasBreadcrumb = IsSectionDefined("Breadcrumb");
}

<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" />
        <title>@ViewBag.Title</title>
    </head>
    <body>
        <header>
            <partial name="_NavigationPartial" />
            <partial name="_BreadcrumbPartial" />
        </header>
        <main class="container-md">
            @RenderBody()
        </main>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    </body>
</html>

Views/Shared/_NavigationPartial.cshtml
<nav class="navbar navbar-expand-lg bg-primary mb-3">
    <div class="container-md">
        <a class="navbar-brand text-light" asp-controller="Home" asp-action="Index">
            @(ViewBag.Brand ?? "Веб-приложение")
        </a>
        <button class="navbar-toggler text-light border-light" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <i class="bi bi-list text-light"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link text-light" asp-controller="Home" asp-action="Index">
                        <i class="bi bi-house"></i>
                        Главная страница
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" asp-controller="Products" asp-action="Index">
                        <i class="bi bi-bag"></i>
                        Список товаров
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" asp-controller="Cart" asp-action="Index">
                        <i class="bi bi-basket3"></i>
                        Корзина
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>